blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.index, name="index"),
    path("post_list/", views.PostListView.as_view(), name="post_list"),
    path("<slug:slug>/", views.PostDetailView.as_view(), name="post_detail"),
    path("like/<slug:slug>/", views.like_post, name="like_post"),
    path(
        "<slug:slug>/edit_comment/<int:comment_id>",
        views.comment_edit,
        name="comment_edit",
    ),
    path(
        "<slug:slug>/delete_comment/<int:comment_id>",
        views.comment_delete,
        name="comment_delete",
    ),
]

contact/urls.py
from django.urls import path
from . import views

app_name = "contact"

urlpatterns = [
    path("", views.contact_view, name="contact"),
]

venture_vibes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from venture_vibes import views

urlpatterns = [
    path("about/", include(("about.urls", "about"), namespace="about")),
    path("accounts/", include("allauth.urls")),
    path("admin/", admin.site.urls),
    path("blog/", include(("blog.urls", "blog"), namespace="blog")),
    path("contact/", include(
        ("contact.urls", "contact"),
        namespace="contact")),
    path("profiles/", include(
        ("profiles.urls", "profiles"),
        namespace="profiles")),
    path("summernote/", include("django_summernote.urls")),
    path("", include(("blog.urls", "blog"), namespace="blog-home")),
]

handler404 = "venture_vibes.views.custom_404_view"
handler500 = "venture_vibes.views.custom_500_view"

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from cloudinary.models import CloudinaryField

# Create your models here.


class Post(models.Model):
    """
    Represents a blog post entry authored by a user,
    related to :model:`auth.User` and :model:`blog.Post`.
    """
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    title = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="blog_posts"
    )
    featured_image = CloudinaryField("image", default="placeholder")
    body = models.TextField()
    excerpt = models.TextField(blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="liked_posts", blank=True
    )
    status = models.CharField(
        max_length=2, choices=Status.choices, default=Status.DRAFT
    )

    class Meta:
        ordering = ["-publish"]

    def __str__(self):
        return self.title


class Comment(models.Model):
    """
    Represents a comment on a blog post authored by a user,
    related to :model:`auth.User` and :model:`blog.Post`.
    """
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments"
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="commenter"
    )
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return f"Comment by {self.author} on {self.post}"

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    """
    A form for submitting comments.
    """
    class Meta:
        model = Comment
        fields = ("body",)

blog/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic, View
from django.contrib import messages
from django.http import HttpResponseRedirect
from .forms import CommentForm
from .models import Post, Comment

# Create your views here.


class PostListView(generic.ListView):
    """
    Renders a list of published blog posts.

    Displays instances of :model:`blog.Post` that are published,
    along with pagination.

    **Context**
    ``posts``
        A queryset of published blog posts.

    **Template**
    :template:`blog/list.html`
    """
    model = Post
    queryset = Post.objects.filter(status=Post.Status.PUBLISHED)
    template_name = "blog/list.html"
    context_object_name = "posts"
    paginate_by = 3


class PostDetailView(View):
    """
    Displays an individual instance of :model:`blog.Post` and allows users to
    submit comments.

    **Context**
    ``post``
        The blog post instance retrieved by slug.

    ``comments``
        A queryset of comments related to the post.

    ``comment_count``
        The number of active comments on the post.

    ``comment_form``
        An instance of :form:`blog.CommentForm`.

    **Template**
    :template:`blog/post_detail.html`
    """
    def get(self, request, slug):
        post = get_object_or_404(Post, slug=slug)
        comments = post.comments.all().order_by("-created")
        comment_count = post.comments.filter(active=True).count()
        comment_form = CommentForm()
        return render(
            request,
            "blog/post_detail.html",
            {
                "post": post,
                "comments": comments,
                "comment_count": comment_count,
                "comment_form": comment_form,
                "user": request.user,
            },
        )

    def post(self, request, slug):
        post = get_object_or_404(Post, slug=slug)
        comment_form = CommentForm(data=request.POST)
        comments = post.comments.all().order_by("-created")
        comment_count = post.comments.filter(active=True).count()

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            messages.add_message(
                request, messages.SUCCESS,
                "Comment submitted and awaiting approval"
            )

            comment_form = CommentForm()

        else:
            messages.add_message(
                request,
                messages.ERROR,
                "Comment has not been submitted due to an Error",
            )

        return render(
            request,
            "blog/post_detail.html",
            {
                "post": post,
                "comments": comments,
                "comment_count": comment_count,
                "comment_form": comment_form,
                "user": request.user,
            },
        )


def comment_edit(request, slug, comment_id):
    """
    Display an individual comment for edit.

    **Context**

    ``post``
        An instance of :model:`blog.Post`.
    ``comment``
        A single comment related to the post.
    ``comment_form``
        An instance of :form:`blog.CommentForm`.
    """
    if request.method == "POST":
        post = get_object_or_404(Post, slug=slug)
        comment = get_object_or_404(Comment, pk=comment_id)
        comment_form = CommentForm(data=request.POST, instance=comment)

        if comment_form.is_valid() and comment.author == request.user:
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.active = False
            comment.save()
            messages.add_message(
                request, messages.SUCCESS,
                "Comment updated and awaiting approval!"
            )
            return HttpResponseRedirect(
                reverse("blog:post_detail", args=[slug])
            )
        else:
            messages.add_message(
                request, messages.ERROR,
                "Error updating comment!"
            )

    return HttpResponseRedirect(
        reverse("blog:post_detail", args=[slug])
    )


def comment_delete(request, slug, comment_id):
    """
    Delete an individual comment.

    **Context**

    ``post``
        An instance of :model:`blog.Post`.
    ``comment``
        A single comment related to the post.
    """
    post = get_object_or_404(Post, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.author == request.user:
        comment.delete()
        messages.add_message(
            request, messages.SUCCESS,
            "Comment deleted successfully!"
        )
    else:
        messages.add_message(
            request, messages.ERROR,
            "You are not allowed to delete this comment."
        )

    return HttpResponseRedirect(
        reverse("blog:post_detail", args=[slug])
    )


def index(request):
    """
    Display the latest published blog post.

    **Context**

    ``latest_post``
        The most recent instance of :model:`blog.Post` that is published.
    """
    latest_post = (
        Post.objects.filter(status=Post.Status.PUBLISHED)
            .order_by("-publish").first()
    )
    return render(
        request,
        "blog/index.html",
        {"latest_post": latest_post},
    )


def like_post(request, slug):
    """
    Toggle like status for a specific blog post.

    **Context**

    ``post``
        An instance of :model:`blog.Post` that is being liked or unliked.
    """
    post = get_object_or_404(Post, slug=slug)
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
    return HttpResponseRedirect(
        reverse("blog:post_detail", args=[slug])
    )

blog/templates/blog/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- Hero section -->
<div class="px-4 py-5 my-5 text-center">
  <h1 class="display-5 fw-bold text-body-emphasis">Welcome to Venture Vibes</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">Follow us as we discover new travel destinations and inspire your next journey</p>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
      {% if user.is_authenticated %}
      <a href="{% url 'blog:post_list' %}" class="btn btn-primary btn-lg px-4 me-md-2">Blog</a>
      <a href="{% url 'contact:contact' %}" class="btn btn-outline-secondary btn-lg px-4">Contact Us</a>
      {% else %}
      <a href="{% url 'blog:post_list' %}" class="btn btn-primary btn-lg px-4 me-md-2">Blog</a>
      <a href="{% url 'account_signup' %}" class="btn btn-outline-secondary btn-lg px-4">Join Us</a>
      {% endif %}
    </div>
  </div>
</div>
<!-- Carousel -->
<div class="container my-5">
  <div id="carouselExampleIndicators" class="carousel slide">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
        aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
        aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
        aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'images/kerlingafjoell.webp' %}" class="d-block w-100 carousel-image" alt="kerlingafjoell">
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/godafoss.webp' %}" class="d-block w-100 carousel-image" alt="godafoss">
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/studlagil_trail.png' %}" class="d-block w-100 carousel-image"
          alt="walking girl at studlagil canyon">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
      data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
      data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>
<!-- Latest Blog Post -->
<div class="container my-5">
  <p class="lead pb-2 text-center border-bottom">Have a look at our latest post</p>
  <div class="p-5 text-center rounded-3 latest-post">
    <h2 class="text-body-emphasis">{{ latest_post.title }}</h2>
    <div class="lead">
      {{ latest_post.excerpt|safe }}
    </div>
    <a href="{% url 'blog:post_detail' latest_post.slug %}" class="icon-link gap-1 icon-link-hover">
      Continue reading</a>
  </div>
</div>

{% endblock %}

blog/templates/blog/list.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container">
    <!-- Hero Section -->
    <div class="px-4 pt-5 my-5 text-center border-bottom">
        <h1 class="display-4 fw-bold text-body-emphasis">Iceland: An Epic Roadtrip Adventure</h1>
        <div class="col-lg-9 mx-auto">
            <p class="lead mb-4">
                Join us as we explore the stunning landscapes and hidden gems of Iceland.
                From majestic waterfalls and geysers to breathtaking glaciers and volcanic formations,
                our roadtrip offers a journey through one of the most unique and beautiful places on Earth.
                Discover the magic of Iceland with us and get inspired for your own adventure!
            </p>
        </div>
        <div class="overflow-hidden" style="max-height: 30vh;">
            <div class="container px-5">
                <img src="{% static 'images/car.webp' %}" class="img-fluid border rounded-3 shadow-lg mb-4"
                    alt="tentcar" width="700" height="500" loading="lazy">
            </div>
        </div>
    </div>
</div>

<div class="container text-center">
    <!-- Blog Cards -->
    <div class="row justify-content-sm-center">
        {% for post in posts %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <h6 class="card-subtitle mb-2 text-body-secondary">{{ post.publish | date:"F j, Y" }} by
                        {{ post.author }}</h6>
                    <div class="card-text">{{ post.excerpt|safe }}</div>
                    <a href="{% url 'blog:post_detail' post.slug %}" class="card-link">Read more</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<div class="container text-center">
    <!-- Pagination Controls -->
    <div class="pagination mt-4  justify-content-sm-center">
        <span class="step-links">
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">&laquo; Previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<!-- Hero Section -->
<div class="container">
  <div class="px-4 pt-5 my-5 text-center border-bottom">
    <h1 class="display-4 fw-bold text-body-emphasis">{{ post.title }}</h1>
    <div class="overflow-hidden" style="max-height: 30vh;">
      <div class="container px-5">
        {% if "placeholder" in post.featured_image.url %}
        <img src="{% static 'images/default.webp' %}" class="img-fluid border rounded-3 shadow-lg mb-4"
          alt="placeholder image" width="700" height="500" loading="lazy">
        {% else %}
        <img src="{{ post.featured_image.url }}" class="img-fluid border rounded-3 shadow-lg mb-4"
          alt="{{ post.title }}" width="700" height="500" loading="lazy">
        {% endif %}
      </div>
    </div>
  </div>
</div>
<!-- Post Detail -->
<div class="container my-5">
  <div class="mb-4">
    {{ post.body|safe }}
  </div>
  <div class="text-muted">
    Published on {{ post.publish|date:"j F, Y" }} by {{ post.author }}
  </div>
  <!-- Like Button -->
  <div class="my-3">
    {% if user.is_authenticated %}
    <p>If you enjoyed this post, leave a like:</p>
    <form action="{% url 'blog:like_post' post.slug %}" method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-link like-button">
        {% if user in post.likes.all %}
        <i class="fas fa-heart liked"></i>
        {% else %}
        <i class="far fa-heart"></i>
        {% endif %}
        <span>{{ post.likes.count }}</span>
      </button>
    </form>
    {% else %}
    <p>You need to <a href="{% url 'account_login' %}">log in</a> to like this post.</p>
    {% endif %}
  </div>
  <a href="{% url 'blog:post_list' %}" class="icon-link gap-1 icon-link-hover">Back to List</a>
</div>
<!-- Comments Section -->
<div class="container my-5">
  <h4>Comments ({{ comment_count }})</h4>
  {% if comments %}
  <ul class="list-unstyled">
    {% for comment in comments %}
    <li class="mb-4">
      <div class="comment-body p-3 border rounded
        {% if not comment.active and comment.author == user %}
        faded{% elif not comment.active %}d-none{% endif %}">
        <p><strong>{{ comment.author }}</strong></p>
        <p id="comment{{ comment.id }}" class="comment-body">{{ comment.body }}</p>

        <p class="text-muted"><em>Posted on {{ comment.created|date:"j F, Y H:i" }}</em></p>
        {% if not comment.active and comment.author == user %}
        <p class="text-muted"><em>This comment is awaiting approval</em></p>
        {% endif %}
        {% if user.is_authenticated and comment.author == user %}
        <button class="btn btn-success btn-edit" data-comment_id="{{ comment.id }}">Edit</button>
        <button type="button" class="btn btn-danger btn-delete" data-comment_id="{{ comment.id }}">Delete</button>
        {% endif %}
      </div>
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <p>No comments yet.</p>
  {% endif %}
</div>
<!-- Comment Form -->
<div class="container my-5">
  <div class="my-4">
    <h4 class="mb-3">Leave a Comment</h4>
    {% if user.is_authenticated %}
    <div class="comment-body p-3 border rounded">
      <form id="commentForm" method="post">
        {{ comment_form | crispy }}
        {% csrf_token %}
        <p class="text-muted">Posting as: {{ user.username }}</p>
        <button id="submitButton" type="submit" class="btn btn-primary mt-3">Submit</button>
      </form>
    </div>
    {% else %}
    <p>You need to <a href="{% url 'account_login' %}">log in</a> to leave a comment.</p>
    {% endif %}
  </div>
</div>

<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete comment?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete your comment?
        This action cannot be undone.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <a id="deleteConfirm" href="#" class="btn
          btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block extras %}
<script src="{% static 'js/comments.js' %}"></script>
{% endblock extras%}