about/urls.py
from django.urls import path
from . import views

app_name = "about"

urlpatterns = [
    path("", views.AboutView.as_view(), name="about"),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.index, name="index"),
    path("post_list/", views.PostListView.as_view(), name="post_list"),
    path("<slug:slug>/", views.PostDetailView.as_view(), name="post_detail"),
    path("like/<slug:slug>/", views.like_post, name="like_post"),
    path(
        "<slug:slug>/edit_comment/<int:comment_id>",
        views.comment_edit,
        name="comment_edit",
    ),
    path(
        "<slug:slug>/delete_comment/<int:comment_id>",
        views.comment_delete,
        name="comment_delete",
    ),
]

profiles/urls.py
from django.urls import path
from .views import user_profile

app_name = "profiles"

urlpatterns = [path("", user_profile, name="user_profile")]

venture_vibes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from venture_vibes import views

urlpatterns = [
    path("about/", include(("about.urls", "about"), namespace="about")),
    path("accounts/", include("allauth.urls")),
    path("admin/", admin.site.urls),
    path("blog/", include(("blog.urls", "blog"), namespace="blog")),
    path("contact/", include(
        ("contact.urls", "contact"),
        namespace="contact")),
    path("profiles/", include(
        ("profiles.urls", "profiles"),
        namespace="profiles")),
    path("summernote/", include("django_summernote.urls")),
    path("", include(("blog.urls", "blog"), namespace="blog-home")),
]

handler404 = "venture_vibes.views.custom_404_view"
handler500 = "venture_vibes.views.custom_500_view"

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description"
    content="Venture Vibes = Follow us on our breathtaking adventures and get inspired for your own next travel.">
  <title>Venture Vibes</title>

  <!-- Internationalization -->
  {% load i18n %}
  <!-- Static Files -->
  {% load static %}
  <!-- Favicon -->
  <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
  <!-- Font Awesome -->
  <script src="https://kit.fontawesome.com/e7f4edf267.js" crossorigin="anonymous"></script>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
  <!-- Header -->
  <div class="container">
    <header
      class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <div class="col-md-3 mb-2 mb-md-0">
        <a href="{% url 'blog:index' %}" class="d-inline-flex align-items-center link-body-emphasis text-decoration-none">
          <img src="{% static 'images/logo.png' %}" alt="logo" width="18">
          Venture Vibes</a>
      </div>

      <!-- Navbar -->
      <nav class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <ul class="nav">
          <li><a href="{% url 'blog:index' %}" class="nav-link px-2">{% trans "Home" %}</a></li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{% url 'blog:index' %}" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              {% trans "Adventures" %}
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'blog:post_list' %}">{% trans "Iceland Roadtrip" %}</a></li>
            </ul>
          </li>
          <li><a href="{% url 'about:about' %}" class="nav-link px-2">{% trans "About" %}</a></li>
        </ul>
      </nav>

      <!-- User Authentication -->
      <div class="col-md-3 text-end">
        {% if user.is_authenticated %}
        <div class="dropdown text-end">
          <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown"
            aria-expanded="false">
            <img src="{% static 'images/nobody.jpg' %}" alt="mdo" width="32" height="32" class="rounded-circle">
          </a>
          <ul class="dropdown-menu dropdown-menu-end text-small">
            <li><a class="dropdown-item" href="{% url 'profiles:user_profile' %}">{% trans "Profile" %}</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="{% url 'account_logout' %}">{% trans "Sign out" %}</a></li>
          </ul>
        </div>
        {% else %}
        <a href="{% url 'account_login' %}" class="btn btn-outline-primary me-2">{% trans "Login" %}</a>
        <a href="{% url 'account_signup' %}" class="btn btn-primary">{% trans "Sign-up" %}</a>
        {% endif %}
      </div>
    </header>
  </div>
  <!-- Alert Messages -->
  {% if messages %}
  <div class="alert-container">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      {{ message|safe }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
  </div>
  {% endif %}
  <main>
    {% block content %}
    {% endblock %}
  </main>
  <!-- footer -->
  <div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
      <div class="col-md-4 d-flex align-items-center">
        <span class="mb-3 mb-md-0 text-body-secondary">© 2024 Venture Vibes</span>
      </div>
      <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
        <li class="ms-3"><a class="text-body-secondary" href="https://x.com/" target="_blank" rel="noopener"
            aria-label="Visit our X page (opens in a new tab)"><i class="fa-brands fa-square-x-twitter"></i></a></li>
        <li class="ms-3"><a class="text-body-secondary" href="https://www.instagram.com/" target="_blank" rel="noopener"
            aria-label="Visit our Instagram page (opens in a new tab)"><i class="fa-brands fa-instagram"></i></a></li>
        <li class="ms-3"><a class="text-body-secondary" href="https://www.facebook.com/" target="_blank" rel="noopener"
            aria-label="Visit our Facebook page (opens in a new tab)"><i class="fa-brands fa-facebook"></i></a></li>
      </ul>
    </footer>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous">
  </script>

  {% block extras %}
  {% endblock %}
</body>

</html>